positions:
  spawn:
    world: "world"
    x: 0
    y: 0
    z: 0
  arena:
    world: "world"
    point1:
      x: 1
      y: 1
      z: 1
    point2:
      x: 2
      y: 2
      z: 2

database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: ""